server:
  port: 8081

spring:
  application:
    name: isolation

  h2:
    console:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: client
    password: guest
    ssl:
      enabled: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 15
    shouldEnforceRegistrationAtInit: true

axon:
  distributed:
    enabled: true

  test:
    auto:
      config: true

management:
  security:
    enabled: false
