server:
  port: 8101

spring:
  application:
    name: business

  h2:
    console:
      enabled: true

  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    url: jdbc:h2:tcp://localhost/~/test # will create a database on <user-home>\test

  rabbitmq:
    host: localhost
    port: 5672
    username: business
    password: business

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 15
    shouldEnforceRegistrationAtInit: true

axon:
  distributed:
    enabled: true

  test:
    auto:
      config: true

logging:
    level:
      com.netflix.eureka: INFO
      com.netflix.discovery: INFO
      org.springframework.web: WARN
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  security:
    enabled: false

