server:
  port: 8082

spring:
  application:
    name: business

  h2:
    console:
      enabled: true

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: client
#    password: guest

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 15
    shouldEnforceRegistrationAtInit: true

axon:
  distributed:
    enabled: true

  test:
    auto:
      config: true

logging:
    level:
      com.netflix.eureka: INFO
      com.netflix.discovery: INFO
      org.springframework.web: WARN
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  security:
    enabled: false

